#!/bin/bash
echo Installing Tools and Programs
apt update
apt install leafpad
apt remove gedit
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
apt-get install apt-transport-https
"deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
apt-get update
snap install sublime-text --classic
apt install git
apt install python3
apt install python3-pip
apt install python-pip
apt install python
echo All Tools and Programs Installed
reboot
